name: Build and deploy reservAC frontend

run-name: ${{ github.actor }} is building the reservAC frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: [reservac]
    
    strategy:
      matrix:
        node-version: [16.18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - shell: bash
        env:
          PASS: ${{ secrets.DALINAR_RUNNERS_PASSWORD }}
        run: |
          echo $PASS | sudo -S mkdir -p /var/www/reservac
          echo $PASS | sudo -S cp -r dist/* /var/www/reservac
